version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server2019
    environment:
      SA_PASSWORD: "SqlServerPw!"
      ACCEPT_EULA: "Y"
    ports:
      - "1432:1433"

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./db/01-Migration.sql:/tmp/01-Migration.sql
      - ./db/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh

  travel_analyzer_dijkstra:
    image: ${DOCKER_REGISTRY-}travel_analyzer_dijkstra
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - mssqltools
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro